//! Keybinding tables: the status-bar hints and the `?` help overlay.
//!
//! Kept apart from `app.rs` so adding a binding is a one-file edit, and so the
//! list stays readable as a list rather than buried in the event loop.

pub const PICKER_HINTS: [(&str, &str); 7] = [
    ("Enter", "connect"),
    ("a", "add"),
    ("e", "edit"),
    ("d", "delete"),
    ("t", "test"),
    ("q", "quit"),
    ("?", "help"),
];

pub const EXPLORER_HINTS: [(&str, &str); 12] = [
    ("Tab", "pane"),
    ("c", "new console"),
    ("g", "erd"),
    ("Ctrl+Enter", "run SQL"),
    ("Enter/Space", "open/expand"),
    ("y/Y", "copy cell/row"),
    ("Ctrl+E", "export"),
    ("e", "edit cell"),
    ("x", "delete row"),
    ("i", "insert row"),
    ("w", "close tab"),
    ("Esc", "picker"),
];

pub const PICKER_HELP_BINDINGS: [(&str, &str); 7] = [
    ("Enter", "connect to selected database"),
    ("a", "add new connection"),
    ("e", "edit selected connection"),
    ("d", "delete selected connection"),
    ("t", "test connection ping"),
    ("q", "quit"),
    ("Esc", "close popup / back"),
];

pub const EXPLORER_HELP_BINDINGS: [(&str, &str); 48] = [
    ("Tab", "toggle focus between Explorer tree & Workspace / subpane"),
    ("c", "open new SQL Query Console tab"),
    ("g", "open In-Terminal ERD diagram for selected database"),
    ("Ctrl+T", "search all objects / jump to a table"),
    ("Ctrl+Enter / Alt+Enter / F5", "execute SQL query in active console"),
    ("Home / End (in editor)", "jump to start / end of line (also Ctrl+A / Ctrl+E)"),
    ("s / S (in table tab)", "add a sort column (asc/desc/off) / clear all sorting"),
    ("Ctrl+B", "collapse / restore the explorer tree"),
    ("Ctrl+Space (in editor)", "ask for autocomplete suggestions"),
    ("Esc (while running)", "cancel the query in flight"),
    ("Ctrl+R", "reconnect after a dropped connection"),
    ("Ctrl+Shift+I", "import rows from a CSV file into the active table"),
    ("Alt+H", "open query history for this connection"),
    ("Alt+F", "open saved query collections"),
    ("Ctrl+S", "save current query to a collection"),
    ("Ctrl+F", "pretty-print SQL in the editor"),
    ("[ / ]", "switch workspace tab (or result set in console)"),
    ("j / Down", "move cursor / selection down"),
    ("k / Up", "move cursor / selection up"),
    ("h / Left", "move cursor / column selection left"),
    ("l / Right", "move cursor / column selection right"),
    ("Space", "expand / collapse database node in tree"),
    ("Enter", "open table in workspace grid"),
    ("s", "sort data grid by active column (asc → desc → off)"),
    ("/", "filter data grid rows (col op value, e.g. status = paid)"),
    ("y / c", "copy active cell value to system clipboard"),
    ("Y / Ctrl+Y", "copy active row as formatted JSON to clipboard"),
    ("Ctrl+E", "open export dialog (CSV, JSON, SQL INSERT, SQL dump, xlsx)"),
    ("e / Enter", "edit active cell value (shows safe SQL confirmation)"),
    ("e (on tree table)", "edit table schema (ALTER: drop/add column, rename)"),
    ("a (in tree)", "create schema / table / view / type / function"),
    ("Ctrl+O (on tree table)", "context menu: view DDL / open rows / edit schema / delete table"),
    ("x", "delete selected row (shows safe SQL confirmation)"),
    ("v (in table tab)", "expand the selected row vertically (wide tables)"),
    ("Ctrl+F / Ctrl+G", "search all cells / jump to the next match"),
    ("E (in ERD tab)", "export the diagram as ~/dbx_erd_<schema>.svg + .mmd"),
    ("Ctrl+W (in console)", "cycle auto re-run: off / 1s / 5s / 15s / 60s"),
    ("Ctrl+T (in console)", "toggle autocommit — off = each run opens a transaction"),
    ("F6 / F7 (in console)", "commit / roll back the open transaction"),
    ("Ctrl+P (in console)", "EXPLAIN the query and show the plan tree"),
    ("f (on an FK cell)", "open the row this foreign key references"),
    ("F (on any cell)", "find every row in the schema that references it"),
    ("Ctrl+K", "list running queries (x cancels, r refreshes)"),
    ("Alt+D", "compare this schema with another saved connection"),
    ("i", "open INSERT-row modal — fill fields, server applies DEFAULT for skipped"),
    ("F1", "view table DDL schema popup"),
    ("n / p", "next / previous page in data grid"),
    ("w", "close active workspace tab"),
];
